name: Stack
version: 0.1-ALPHA
main: com.mcteekung.stack.Stack
api-version: 1.13
author: _MCTEEKUNG_
description: Displays the count of dropped items.
commands:
  stack:
    description: Main command for the Stack plugin.
    usage: /<command> [on|off|reload|help]
    aliases: [st]
